# Generated by Django 3.1.6 on 2024-03-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_ads_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='feature',
        ),
    ]
